name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests without starting a server
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload selected fixture files
        uses: actions/upload-artifact@v4
        with:
          name: selected-fixtures
          path: |
            cypress/fixtures/validationResults.json


